### PR TITLE
remove node-sds from package.json because this module is coming with …

### PR DESCRIPTION
**Pull request by tineheller**
…node-documents-scripting module

I'm not really sure if I've understood which modules I have to list in dependencies because it does not behave as I expect.

### CODE REVIEW

**Comment by bkircher** [comment]
For this I wouldn't use a PR. Your comment above even looks like a question.

**Comment by wehrstedt** [comment]
If this module is required for the execution of this extension, then this module has to be listed in the dependencies.

The reason:
When the dependency "node-sds" inside the module "node-documents-scripting" will be removed, the extension will not work anymore.
Every module this extension depends on needs to be listed in the dependencies, even if they comes with a "sub-dependency"...

**Comment by tineheller** [comment]
Well, no, this module is only required, if node-documents-scripting is required. So actually, if node-documents-scripting is removed, node-sds can be removed too. There is no dependency to node-sds, only to node-documents-scripting. So I think it should be ok to remove node-sds...?

**Comment by wehrstedt** [comment]
Ok, then this commit is correct.

**Comment by bkircher** [comment]
> Ok, then this commit is correct.

Yes. There are no direct uses of node-sds in this code anymore so the dependency can be dropped.

**Pull request merged**
